apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: exx5j6rq6-python
  janus-idp.io/tekton: exx5j6rq6-python
  backstage.io/kubernetes-id: exx5j6rq6-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: exx5j6rq6-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
